### ISSUE TITLE
App Store Checklist

### ISSUE THREAD

**Issue by stevefosterwta** [willowtreeapps/eyespeak-ios#332]
- [x] Localized "What's new..."
- [x] Localized "Description - Italian"
- [x] Inform WT Marketing
- [x] Localized screenshots 
- [x] App Submission 

https://docs.google.com/document/d/1dCwunA6FCJgmi4HeYEmpHXjN0HOs6XwzQ_HkPBDVDPo/edit?usp=sharing
