### ISSUE TITLE
Unlink the Chained UI Tests!

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/eyespeak-ios#405]
Currently, UI tests for iOS are dependent on each other, which causes issues if one were to stop working. We need to unlink and make each test independent of each other.

Creating a [Task List](https://docs.github.com/en/issues/tracking-your-work-with-issues/quickstart#adding-a-task-list) for sub-tasks of this parent ticket. We will update this list as it grows.

- [x] Unlink CustomCategoriesTests Class' tests #464 
    - [x] Re-enable tests; refactor to leverage `resetAtLaunch` build launch argument #511 
- [x] Handle the CustomCategoriesTests::testPagination test #470 
- [x] Fix the SettingScreenTests::testAddCustomCategory test #514  
- [x] Fix the KeyboardScreenTests #466 
- [x] Fix the SettingScreenTests #480
- [x] Re-enable and Fix the MainScreenTests #526  
- [x] Fix other (if any) failing tests
    - [x] SettingsScreenTests we disabled for the design changes on Settings > Categories screen
