### ISSUE TITLE
Refactor UI tests to use injection data

### ISSUE THREAD

**Issue by rowildcard** [willowtreeapps/eyespeak-ios#590]
This is the parent issue for using injection data in automation:

- [x] [Allow preset data injection for testing purposes, 587](https://github.com/willowtreeapps/vocable-ios/issues/587)
- [x] [Refactor MainScreenTests to use injection data, 636](https://github.com/willowtreeapps/vocable-ios/issues/636)
- [x] [Refactor SettingsTests to use injection data, 588](https://github.com/willowtreeapps/vocable-ios/issues/588)
- [x] [Refactor CategoryPhrasesPaginationTests to use injection data, 589](https://github.com/willowtreeapps/vocable-ios/issues/589)
- [x] [Refactor PresetPhraseTests to use injection data, 638](https://github.com/willowtreeapps/vocable-ios/issues/638)
- [x] [Add Preset Category Tests (existing WIP that needs to be refactored), 569](https://github.com/willowtreeapps/vocable-ios/issues/569)

**Comment by rhsalas3** [comment]
All items required for this ticket, as outlined in the checklist of the description, have been completed. I am going to mark this ticket as done!
